# ClaimVisualizer Configuration File

# Global Particle Settings (fallback values)
particles:
  # Player view angle range (in degrees) - The angle range in which particles are displayed
  view-angle-range: 150

# Display mode specific settings
display-modes:
  CORNERS:
    # Update frequency (in ticks)
    update-interval: 20
    # Render distance (in blocks)
    render-distance: 30
    # Particle spacing (in blocks)
    spacing: 1.0
    # Particle display interval (in ticks) - How often to display a batch of particles
    display-interval: 2
    # Corner size in blocks
    corner-size: 5
  
  OUTLINE:
    # Update frequency (in ticks)
    update-interval: 10
    # Render distance (in blocks)
    render-distance: 25
    # Particle spacing (in blocks)
    spacing: 0.5
    # Particle display interval (in ticks)
    display-interval: 1
    # Outline display radius
    outline-radius: 10.5
  
  FULL:
    # Update frequency (in ticks)
    update-interval: 10
    # Render distance (in blocks)
    render-distance: 20
    # Particle spacing (in blocks)
    spacing: 0.6
    # Particle display interval (in ticks)
    display-interval: 1
    # Vertical render range (in blocks) - Only render particles within this range above/below the player
    vertical-render-range: 15
    # Adaptive density - Increase particle density based on player's view angle
    adaptive-density: true
    # Focus factor - Increase particle density based on player's focus
    focus-factor: 1.5
    # Fade distance - Distance from the player where particles start to fade out
    fade-distance: 0.8
    # Fade factor - Particle brightness fade factor
    top-brightness: 1.2
    # Fade factor - Particle brightness fade factor
    bottom-brightness: 0.8
  
  WALL:
    # Update frequency (in ticks)
    update-interval: 10
    # Render distance (in blocks)
    render-distance: 15
    # Particle spacing (in blocks)
    spacing: 0.5
    # Particle display interval (in ticks)
    display-interval: 1
    # Wall mode display radius
    wall-radius: 3.5
    # Adaptive density - 動態調整粒子密度
    adaptive-density: true
    # Focus factor - 視線焦點增強係數
    focus-factor: 1.8
    # Fade distance - 淡出距離係數
    fade-distance: 0.7
    # Edge emphasis - 邊緣強調係數
    edge-emphasis: 2.0
    # Wave effect - 波浪效果
    wave-effect: true
    # Wave speed - 波浪速度
    wave-speed: 1.0
    # Wave intensity - 波浪強度
    wave-intensity: 0.3
    # 視角效果強度 (0-1)，決定視線中心與邊緣的渲染半徑差異
    # 0 表示無效果，1 表示視線邊緣的範圍為中心的 0%
    view-angle-effect: 0.6
  
# Particle settings for different claim types
claim-types:
  admin:
    # Bottom frame
    bottom:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Top frame
    top:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Horizontal line at player's height
    horizontal:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Vertical connecting lines
    vertical:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
  basic:
    bottom:
      particle: REDSTONE
      color:
        red: 0
        green: 255
        blue: 0
    top:
      particle: REDSTONE
      color:
        red: 0
        green: 200
        blue: 0
    horizontal:
      particle: REDSTONE
      color:
        red: 0
        green: 255
        blue: 0
    vertical:
      particle: REDSTONE
      color:
        red: 40
        green: 255
        blue: 40
  subdivision:
    bottom:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 255
    top:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 200
    horizontal:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 255
    vertical:
      particle: REDSTONE
      color:
        red: 100
        green: 100
        blue: 255
  town:
    bottom:
      particle: REDSTONE
      color:
        red: 255
        green: 255
        blue: 0
    top:
      particle: REDSTONE
      color:
        red: 255
        green: 200
        blue: 0
    horizontal:
      particle: REDSTONE
      color:
        red: 255
        green: 255
        blue: 0
    vertical:
      particle: REDSTONE
      color:
        red: 255
        green: 180
        blue: 0

# Performance Settings
performance:
  # Maximum number of claims rendered simultaneously
  max-claims: 10
  # Use asynchronous rendering
  async-rendering: true
  # Cache time (in seconds)
  cache-time: 10

# Display Settings
display:
  # Display mode: CORNERS (corner only), OUTLINE (outline only), FULL (complete boundary), WALL (wall surface)
  mode: OUTLINE
  # Show own claims
  show-own-claims: true
  # Show others' claims
  show-others-claims: true
  # Show admin claims
  show-admin-claims: true
  # Show town claims
  show-town-claims: true
