# ClaimVisualizer Configuration File

# Particle Settings
particles:
  # Update frequency (in ticks)
  update-interval: 10
  # Render distance (in blocks)
  render-distance: 20
  # Particle spacing (in blocks)
  spacing: 1.0
  # Particle display height (relative to ground)
  height: 1.0
  # Particle display interval (in ticks) - How often to display a batch of particles
  display-interval: 1
  
# Particle settings for different claim types
claim-types:
  admin:
    # Bottom frame
    bottom:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Top frame
    top:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Horizontal line at player's height
    horizontal:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
    # Vertical connecting lines
    vertical:
      particle: REDSTONE
      color: 
        red: 255
        green: 0
        blue: 0
  basic:
    bottom:
      particle: REDSTONE
      color:
        red: 0
        green: 255
        blue: 0
    top:
      particle: REDSTONE
      color:
        red: 0
        green: 200
        blue: 0
    horizontal:
      particle: REDSTONE
      color:
        red: 0
        green: 255
        blue: 0
    vertical:
      particle: REDSTONE
      color:
        red: 40
        green: 255
        blue: 40
  subdivision:
    bottom:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 255
    top:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 200
    horizontal:
      particle: REDSTONE
      color:
        red: 0
        green: 0
        blue: 255
    vertical:
      particle: REDSTONE
      color:
        red: 100
        green: 100
        blue: 255
  town:
    bottom:
      particle: REDSTONE
      color:
        red: 255
        green: 255
        blue: 0
    top:
      particle: REDSTONE
      color:
        red: 255
        green: 200
        blue: 0
    horizontal:
      particle: REDSTONE
      color:
        red: 255
        green: 255
        blue: 0
    vertical:
      particle: REDSTONE
      color:
        red: 255
        green: 180
        blue: 0

# Performance Settings
performance:
  # Maximum number of claims rendered simultaneously
  max-claims: 10
  # Use asynchronous rendering
  async-rendering: true
  # Cache time (in seconds)
  cache-time: 10

# Display Settings
display:
  # Display mode: CORNERS (corner only), OUTLINE (outline only), FULL (complete boundary), WALL (wall surface)
  mode: OUTLINE
  # Show own claims
  show-own-claims: true
  # Show others' claims
  show-others-claims: true
  # Show admin claims
  show-admin-claims: true
  # Show town claims
  show-town-claims: true
  # Wall mode display radius
  wall-radius: 3.0
  # OUTLINE mode display radius
  outline-radius: 4.0
