name: ClaimVisualizer
version: '${project.version}'
main: dev.twme.claimVisualizer.ClaimVisualizer
api-version: '1.21'
depend: [GriefDefender]
description: Visualize claim boundaries using particle effects
authors: [twme]
commands:
  claimvisual:
    description: Main command for claim visualization plugin
    usage: /claimvisual [on|off|reload|help|mode|language|debug]
    aliases: [cv, claimviz]
permissions:
  claimvisualizer.use:
    description: Allow using basic visualization features
    default: true
  claimvisualizer.reload:
    description: Allow reloading plugin configuration
    default: op
  claimvisualizer.language:
    description: Allow changing plugin display language
    default: true
  claimvisualizer.autoenable:
    description: Automatically enable claim visualization when joining the server
    default: false
  claimvisualizer.debug:
    description: Allow using debug commands
    default: op
