name: ClaimVisualizer
version: '0.0.1'
main: dev.twme.claimVisualizer.ClaimVisualizer
api-version: '1.21'
depend: [GriefDefender]
description: 使用粒子效果視覺化顯示領地邊界
authors: [twme]
commands:
  claimvisual:
    description: 領地視覺化插件主命令
    usage: /claimvisual [on|off|reload|help]
    aliases: [cv, claimviz]
permissions:
  claimvisualizer.use:
    description: 允許使用基本視覺化功能
    default: true
  claimvisualizer.reload:
    description: 允許重新載入插件配置
    default: op
